short_chained = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "C1_0": "Formic Acid (HCOOH)",
    "C2_0": "Acetic Acid (C2H4O2)",
    "C3_0": "Propionic Acid (C3H6O2)",
    "C4_0": "Butyric Acid (C4H803)",
    "C5_0": "Valeric Acid",
    "X2_HYDROXYBUTYRIC_ACID": "2-Hydroxybutyric Acid (C4H803)",
    "X3_HYDROXYBUTYRIC_ACID": "3-Hydroxybutyric Acid (C4H8O3)",
    "ISOBUTYRIC_ACID": "Isobutyric Acid (C4H803)",
}
medium_chained = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "C6_0": "Hexanoic Acid (C6H1202)",
    "X__2_METHYLPENTANOIC_ACID": "()-2-Methylpentanoic acid (C6H1202)",
    "C7_0": "Heptanoic Acid (C7H1402)",
    "C8_0": "Caprylic Acid (C8H1602)",
    "C9_0": "Pelargonic Acid (C8H1802)",
    "C10_0": "Decanoic Acid (C10H20O2)",
    "C11_0": "Undecanoic Acid (C11H22O2)",
    "C11_1_CIS_10": "Undecylenic Acid (C11H20O2)",
}
long_chained = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "C12_0": "Dodecanoic Acid (C12H24O2)",
    "C13_0": "Tridecanoic Acid (C13H26O2)",
    "C14_0": "Myristic Acid (C14H28O2)",
    "C15_0": "Pentadecanoic Acid (C15H30O2)",
    "C16_0": "Palmitic Acid (C16H32O2)",
    "C16_1_CIS_9": "Palmitoleic Acid (C16H30O2)",
    "C17_0": "Heptadecanoic Acid (C17H34O2)",
    "C17_1_CIS_10": "10Z-Heptadecenoic Acid (C17H31O2)",
    "C18_0": "Stearic Acid (C18H36O2)",
    "C18_1_CIS_9": "Oleic Acid (C18H34O2)",
    "C18_2_CIS_9_12": "Linoleic Acid (C18H32O2)",
    "C18_3_CIS_6_9_12": "Gamma-Linolenic Acid (C18H30O2)",
    "C18_3_CIS_9_12_15": "Alpha-Linolenic Acid (C18H30O2)",
    "C19_2_CIS_10_13": "10,13-Nonadecadienoic Acid (C19H34O)",
    "C20_2_CIS_11_14": "Eicosadienoic Acid (C20H36O2)",
    "C20_3_CIS_8_11_14": "8,11,14-Eicosatrienoic Acid (C20H34O2)",
    "C20_4_CIS_5_8_11_14": "Arachidonic Acid (C20H32O2)",
    "C20_5_CIS_5_8_11_14_17": "Eicosapentaenoic Acid (C20H30O2)",
    "C22_6_CIS_4_7_10_13_16_19": "Docosahexaenoic Acid (C22H32O2)",
    "C22_4_CIS_7_10_13_16": "Docosatetraenoic Acid (C22H36O2)",
    "C22_5_CIS_4_7_10_13_16": "all-cis-4,7,10,13,16-docosapentaenoic acid (C22H34O2) ",
    "C22_5_CIS_7_10_13_16_19": "all-cis-7,10,13,16,19-docosapentaenoic acid",
}

amino_acids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "L_HISTIDINE": "L-Histidine",
    "L_LYSINE": "L-Lysine",
    "L_SERINE": "L-Serine",
    "BETA_ALANINE": "Beta Alanine",
    "L_ALANINE": "L-Alanine",
    "L_TYROSINE": "L-Tyrosine",
    "L_ASPARAGINE": "L-Aspargine",
    "L_ASPARTIC_ACID": "L-Aspartic Acid",
    "GLYCINE": "Glycine",
    "L_PROLINE": "L-Proline",
    "L_ALPHA_AMINOBUTYRIC_ACID": "L-Alpha Amiobutyric Acid",
    "PYROGLUTAMIC_ACID": "Pyroglutamic Acid",
    "L_VALINE": "L-Valine",
    "L_METHIONINE": "L-Methionine",
    "L_LEUCINE": "L-Leucine",
    "L_TRYPTOPHAN": "L-Tryptophan",
}

organic_acids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "HIPPURIC_ACID": "Hippuric Acid",
    "L_MALIC_ACID": "L-Malic Acid",
    "ADIPIC_ACID": "Adipic Acid",
    "GLYCERIC_ACID": "Glyceric Acid",
    "GLYCOLIC_ACID": "Glycolic Acid",
    "CIS_ACONITIC_ACID": "cis-Aconitic Acid",
    "METHYLSUCCINIC_ACID": "Methylsuccinic Acid",
    "ISOCITRIC_ACID": "Isocitric Acid",
    "CITRIC_ACID": "Citric Acid",
    "OXOGLUTARIC_ACID": "Oxoglutaric Acid",
    "SUBERIC_ACID": "Suberic acid",
    "SUCCINIC_ACID": "Succinic acid",
    "X3_HYDROXYISOVALERIC_ACID": "3-Hydroxyisovaleric Acid",
}

indole_compounds = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "INDOLEACETIC_ACID": "Indoleacetic Acid",
    "X3_INDOLEPROPIONIC_ACID": "Indolepropionic Acid",
    "X3_METHYL_2_OXOVALERIC_ACID": "3-Methyl-2-oxovaleric Acid",
}

bile_acids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "CA": "Cholic Acid",
    "CDCA": "Chenodeoxycholic Acid",
    "DCA": "Deoxycholic Acid",
    "LCA": "Lithocholic Acid",
    "DEHYDROLCA": "Dehydrolithocholic Acid",
    "UDCA": "Ursodeoxycholic Acid",
    "UCA": "Ursocholic Acid",
    "BUDCA": "3-Ursodeoxycholic Acid (Isoursodeoxycholic acid)",
    "HCA": "Muricholic Acid/Hyocholic Acid",
    "HDCA": "Hyodeoxycholic Acid",
}

oxidized_bile_acids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "X12_KETOLCA": "12-Ketolithocholic Acid",
    "X7_KETOLCA": "7-Ketolithocholic Acid",
    "X3_DHCA": "3-Dehydrocholic Acid",
    "X7_DHCA": "7-Dehydrocholic Acid",
}

glycine_conjugated = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "GCA": "Glycocholic Acid",
    "GCDCA": "Glycochenodeoxycholic Acid",
    "GDCA": "Glycodeoxycholic Acid",
    "GLCA": "Glycolithocholic Acid",
    "GUDCA": "Glycoursodeoxycholic Acid",
    "GHCA": "Glycohyocholic Acid",
    "GHDCA": "Glycohyodeoxycholic Acid",
}

taurine_conjugated = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TCA": "Taurocholic Acid",
    "TCDCA": "Taurochenodeoxycholic Acid",
    "TDCA": "Taurodeoxycholic Acid",
    "TUDCA": "Tauroursodeoxycholic Acid",
    "TAMCA": "Tauro-muricholic Acid",
}

isomeric_and_rare = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "ALLOLCA": "Allolithocholic Acid (Isoallolithocholic acid)",
    "ISOLCA": "Isolithocholic Acid",
    "MUROCA": "Murocholic Acid",
    "NORCA": "Norcholic Acid",
    "NORDCA": "23-Nordeoxycholic Acid",
    "APOCA": "Apocholic Acid",
    "LCA_3S": "Lithocholic Acid 3-Sulfate",
}

others = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "P_CRESOL_SULFATE": "p-Cresol Sulfate",
}

all_metabolites = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "C1_0": "Formic Acid (HCOOH)",
    "C2_0": "Acetic Acid (C2H4O2)",
    "C3_0": "Propionic Acid (C3H6O2)",
    "C4_0": "Butyric Acid (C4H803)",
    "X2_HYDROXYBUTYRIC_ACID": "2-Hydroxybutyric Acid (C4H803)",
    "X3_HYDROXYBUTYRIC_ACID": "3-Hydroxybutyric Acid (C4H8O3)",
    "ISOBUTYRIC_ACID": "Isobutyric Acid (C4H803)",
    "C6_0": "Hexanoic Acid (C6H1202)",
    "C7_0": "Heptanoic Acid (C7H1402)",
    "C8_0": "Caprylic Acid (C8H1602)",
    "C9_0": "Pelargonic Acid (C8H1802)",
    "C10_0": "Decanoic Acid (C10H20O2)",
    "C11_0": "Undecanoic Acid (C11H22O2)",
    "C11_1_CIS_10": "Undecylenic Acid (C11H20O2)",
    "C12_0": "Dodecanoic Acid (C12H24O2)",
    "C13_0": "Tridecanoic Acid (C13H26O2)",
    "C14_0": "Myristic Acid (C14H28O2)",
    "C15_0": "Pentadecanoic Acid (C15H30O2)",
    "C16_0": "Palmitic Acid (C16H32O2)",
    "C16_1_CIS_9": "Palmitoleic Acid (C16H30O2)",
    "C17_0": "Heptadecanoic Acid (C17H34O2)",
    "C17_1_CIS_10": "10Z-Heptadecenoic Acid (C17H31O2)",
    "C18_0": "Stearic Acid (C18H36O2)",
    "C18_1_CIS_9": "Oleic Acid (C18H34O2)",
    "C18_2_CIS_9_12": "Linoleic Acid (C18H32O2)",
    "C18_3_CIS_6_9_12": "Gamma-Linolenic Acid (C18H30O2)",
    "C18_3_CIS_9_12_15": "Alpha-Linolenic Acid (C18H30O2)",
    "C19_2_CIS_10_13": "10,13-Nonadecadienoic Acid (C18H34O)",
    "C20_2_CIS_11_14": "Eicosadienoic Acid (C20H36O2)",
    "C20_3_CIS_8_11_14": "8,11,14-Eicosatrienoic Acid (C20H34O2)",
    "C20_4_CIS_5_8_11_14": "Arachidonic Acid (C20H32O2)",
    "C20_5_CIS_5_8_11_14_17": "Eicosapentaenoic Acid (C20H30O2)",
    "C22_6_CIS_4_7_10_13_16_19": "Docosahexaenoic Acid (C22H32O2)",
    "C22_4_CIS_7_10_13_16": "Docosatetraenoic Acid (C22H36O2)",
    "C22_5_CIS_4_7_10_13_16": "Docosapentaenoic Acid (C22H34O2) ",
    "C22_5_CIS_7_10_13_16_19": "Docosapentaenoic Acid (C22H34O2)",
    "L_HISTIDINE": "L-Histidine",
    "L_LYSINE": "L-Lysine",
    "L_SERINE": "L-Serine",
    "BETA_ALANINE": "Beta Alanine",
    "L_ALANINE": "L-Alanine",
    "L_TYROSINE": "L-Tyrosine",
    "L_ASPARAGINE": "L-Aspargine",
    "L_ASPARTIC_ACID": "L-Aspartic Acid",
    "GLYCINE": "Glycine",
    "L_PROLINE": "L-Proline",
    "L_ALPHA_AMINOBUTYRIC_ACID": "L-Alpha Amiobutyric Acid",
    "PYROGLUTAMIC_ACID": "Pyroglutamic Acid",
    "L_VALINE": "L-Valine",
    "L_METHIONINE": "L-Methionine",
    "L_LEUCINE": "L-Leucine",
    "L_TRYPTOPHAN": "L-Tryptophan",
    "HIPPURIC_ACID": "Hippuric Acid",
    "L_MALIC_ACID": "L-Malic Acid",
    "ADIPIC_ACID": "Adipic Acid",
    "GLYCERIC_ACID": "Glyceric Acid",
    "GLYCOLIC_ACID": "Glycolic Acid",
    "CIS_ACONITIC_ACID": "cis-Aconitic Acid",
    "METHYLSUCCINIC_ACID": "Methylsuccinic Acid",
    "ISOCITRIC_ACID": "Isocitric Acid",
    "CITRIC_ACID": "Citric Acid",
    "OXOGLUTARIC_ACID": "Oxoglutaric Acid",
    "INDOLEACETIC_ACID": "Indoleacetic Acid",
    "X3_INDOLEPROPIONIC_ACID": "Indolepropionic Acid",
    "X3_METHYL_2_OXOVALERIC_ACID": "3-Methyl-2-oxovaleric Acid",
    "CA": "Cholic Acid",
    "CDCA": "Chenodeoxycholic Acid",
    "DCA": "Deoxycholic Acid",
    "LCA": "Lithocholic Acid",
    "DEHYDROLCA": "Dehydrolithocholic Acid",
    "UDCA": "Ursodeoxycholic Acid",
    "UCA": "Ursocholic Acid",
    "BUDCA": "3-Ursodeoxycholic Acid (Isoursodeoxycholic acid)",
    "X12_KETOLCA": "12-Ketolithocholic Acid",
    "X7_KETOLCA": "7-Ketolithocholic Acid",
    "X3_DHCA": "3-Dehydrocholic Acid",
    "X7_DHCA": "7-Dehydrocholic Acid",
    "GCA": "Glycocholic Acid",
    "GCDCA": "Glycochenodeoxycholic Acid",
    "GDCA": "Glycodeoxycholic Acid",
    "GLCA": "Glycolithocholic Acid",
    "GUDCA": "Glycoursodeoxycholic Acid",
    "GHCA": "Glycohyocholic Acid",
    "GHDCA": "Glycohyodeoxycholic Acid",
    "TCA": "Taurocholic Acid",
    "TCDCA": "Taurochenodeoxycholic Acid",
    "TDCA": "Taurodeoxycholic Acid",
    "TUDCA": "Tauroursodeoxycholic Acid",
    "TAMCA": "Tauro-muricholic Acid",
    "ALLOLCA": "Allolithocholic Acid (Isoallolithocholic acid)",
    "ISOLCA": "Isolithocholic Acid",
    "MUROCA": "Murocholic Acid",
    "NORCA": "Norcholic Acid",
    "NORDCA": "23-Nordeoxycholic Acid",
    "APOCA": "Apocholic Acid",
    "LCA_3S": "Lithocholic Acid 3-Sulfate",
    "P_CRESOL_SULFATE": "p-Cresol Sulfate",
    "HCA": "Muricholic Acid/Hyocholic Acid",
    "HDCA": "Hyodeoxycholic Acid",
    "SUBERIC_ACID": "Suberic acid",
    "SUCCINIC_ACID": "Succinic acid",
    "X3_HYDROXYISOVALERIC_ACID": "3-Hydroxyisovaleric Acid",
    "X__2_METHYLPENTANOIC_ACID": "()-2-Methylpentanoic acid",
    "C5_0": "Valeric Acid",
}
