cholesterol = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_C": "Total Cholesterol (mmol/l)",
    "NON_HDL_C": "Non-HDL Cholesterol (mmol/l)",
    "REMNANT_C": "Remnant cholesterol; non-HDL, non-LDL -cholesterol (mmol/l)",
    "VLDL_C": "Cholesterol in VLDL particles (mmol/l)",
    "CLINICAL_LDL_C": "Clinical LDL Cholesterol (mmol/l)",
    "LDL_C": "Cholesterol in LDL (mmol/l)",
    "HDL_C": "Cholesterol in HDL (mmol/l)",
}

triglycerides = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_TG": "Total Triglycerides (mmol/l)",
    "VLDL_TG": "Triglycerides in VLDL particles (mmol/l)",
    "LDL_TG": "Triglycerides in LDL particles (mmol/l)",
    "HDL_TG": "Triglycerides in HDL particles (mmol/l)",
}

phospholipids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_PL": "Total Phospholipids (mmol/l)",
    "VLDL_PL": "Phospholipids in VLDL particles (mmol/l)",
    "LDL_PL": "Phospholipids in LDL particles (mmol/l)",
    "HDL_PL": "Phospholipids in HDL particles (mmol/l)",
}

cholesteryl_esters = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_CE": "Total Cholesteryl Esters (mmol/l)",
    "VLDL_CE": "Cholesteryl Esters in HDL particles (mmol/l)",
    "LDL_CE": "Cholesteryl Esters in HDL particles (mmol/l)",
    "HDL_CE": "Cholesteryl Esters in HDL particles (mmol/l)",
}

free_cholesterol = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_FC": "Total Free Cholesterol (mmol/l)",
    "VLDL_FC": "Free Cholesterol in VLDL particles (mmol/l)",
    "LDL_FC": "Free Cholesterol in LDL particles (mmol/l)",
    "HDL_FC": "Free Cholesterol in HDL particles (mmol/l)",
}

lipids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_L": "Total Lipids (mmol/l)",
    "VLDL_L": "Lipids in VLDL particles (mmol/l)",
    "LDL_L": "Lipids in LDL particles (mmol/l)",
    "HDL_L": "Lipids in HDL particles (mmol/l)",
}

lipoproteins = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_P": "Total Lipoprotein Particle Concentrations (mmol/l)",
    "VLDL_P": "Very Low Density Lipoprotein Particles (mmol/l)",
    "LDL_P": "Low Density Lipoprotein Particles (mmol/l)",
    "HDL_P": "High Density Lipoprotein Particles(mmol/l)",
    "VLDL_SIZE": "Size of VLDL (nm)",
    "LDL_SIZE": "Size of LDL (nm)",
    "HDL_SIZE": "Size of HDL (nm)",
}

other_lipids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "PHOSPHOGLYC": "Phosphoglycerides(mmol/l)",
    "TG_BY_PG": "Ratio of Triglycerides to Phosphoglycerides",
    "CHOLINES": "Cholines (mmol/l)",
    "PHOSPHATIDYLC": "Phosphatidylcholines (mmol/l)",
    "SPHINGOMYELINS": "Sphingomyelins (mmol/l)",
}

alipoproteins = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "APOB": "Apolipoprotein B (g/l)",
    "APOA1": "Apolipoprotein A-1 (g/l)",
    "APOB_BY_APOA1": "Ratio of Apolipoprotein B to Apolipoprotein A-1",
}

fatty_acids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_FA": "Total Fatty Acids",
    "UNSATURATION": "Estimated Degree of Unsaturation",
    "OMEGA_3": "Omega-3 Fatty Acids (mmol/l)",
    "OMEGA_6": "Omega-6 Fatty Acids (mmol/l)",
    "PUFA": "Polyunsaturated Fatty Acids (mmol/l)",
    "MUFA": "Monounsaturated Fatty Acids; 16:1, 18:1 (mmol/l)",
    "SFA": "Saturated Fatty Acids (mmol/l)",
    "LA": "18:2, Linoleic Acid (mmol/l)",
    "DHA": "22:6, Docosahexaenoic Acid (mmol/l)",
    "OMEGA_3_PCT": "Omega-3 Fatty Acids (%)",
    "OMEGA_6_PCT": "Omega-6 Fatty Acids (%)",
    "PUFA_PCT": "Polyunsaturated Fatty Acids (%)",
    "MUFA_PCT": "Monounsaturated Fatty Acids (%)",
    "SFA_PCT": "Saturated Fatty Acids (%)",
    "LA_PCT": "18:2, Linoleic Acid (%)",
    "DHA_PCT": "22:6, Docosahexaenoic Acid (%)",
    "PUFA_BY_MUFA": "Ratio of Polyunsaturated to Monounsaturated Fatty Acids ",
    "OMEGA_6_BY_OMEGA_3": "Ratio of Omega-6 to Omega-3 Fatty Acids",
}

amino_acids = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "ALA": "Alanine (mmol/l)",
    "GLN": "Glutamine (mmol/l)",
    "GLY": "Glycine (mmol/l)",
    "HIS": "Histidine (mmol/l)",
    "TOTAL_BCAA": "Total Concentration of Branced-Chain Amino Acids (mmol/l)",
    "ILE": "Isoleucine (mmol/l)",
    "LEU": "Leucine (mmol/l)",
    "VAL": "Valine (mmol/l)",
    "PHE": "Phenylalanine (mmol/l)",
    "TYR": "Tyrosine (mmol/l)",
}

glycolysis_related = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "GLUCOSE": "Glucose (mmol/l)",
    "LACTATE": "Lactate (mmol/l)",
    "PYRUVATE": "Pyruvate (mmol/l)",
    "CITRATE": "Citrate (mmol/l)",
    "GLYCEROL": "Glycerol (mmol/l)",
}

ketone_bodies = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "BOHBUTYRATE": "β-hydroxybutyrate (mmol/l)",
    "ACETATE": "Acetate (mmol/l)",
    "ACETOACETATE": "Acetoacetate (mmol/l)",
}

fluid_balance_inflammation = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "CREATININE": "Creatinine (µmol/l)",
    "ALBUMIN": "Albumin (g/l)",
    "GLYCA": "GlycA Inflammatory Biomarker (mmol/l)",
}

extremely_large_VLDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "XXL_VLDL_P": "Chylomicrons and extremely large VLDL Particles (mmol/l)",
    "XXL_VLDL_L": "Total lipids in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_PL": "Phospholipids in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_C": "Total cholesterol in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_CE": "Cholesterol esters in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_FC": "Free cholesterol in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_TG": "Triglycerides in chylomicrons and extremely large VLDL (mmol/l)",
}

very_large_VLDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "XL_VLDL_P": "Concentration of very large VLDL particles (mmol/l)",
    "XL_VLDL_L": "Total lipids in very large VLDL  (mmol/l)",
    "XL_VLDL_PL": "Phospholipids in very large VLDL (mmol/l)",
    "XL_VLDL_C": "Total cholesterol in very large VLDL (mmol/l)",
    "XL_VLDL_CE": "Cholesterol esters in very large VLDL (mmol/l)",
    "XL_VLDL_FC": "Free cholesterol in very large VLDL (mmol/l)",
    "XL_VLDL_TG": "Triglycerides in very large VLDL (mmol/l)",
}

large_VLDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "L_VLDL_P": "Concentration of large VLDL particles(mmol/l)",
    "L_VLDL_L": "Total lipids in large VLDL (mmol/l)",
    "L_VLDL_PL": "Phospholipids in large VLDL (mmol/l)",
    "L_VLDL_C": "Total cholesterol in large VLDL (mmol/l)",
    "L_VLDL_CE": "Cholesterol esters in large VLDL (mmol/l)",
    "L_VLDL_FC": "Free cholesterol in large VLDL (mmol/l)",
    "L_VLDL_TG": "Triglycerides in large VLDL (mmol/l)",
}

medium_VLDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "M_VLDL_P": "Concentration of medium VLDL particles (mmol/l)",
    "M_VLDL_L": "Total lipids in medium VLDL (mmol/l)",
    "M_VLDL_PL": "Phospholipids in medium VLDL (mmol/l)",
    "M_VLDL_C": "Total cholesterol in medium VLDL (mmol/l)",
    "M_VLDL_CE": "Cholesterol esters in medium VLDL (mmol/l)",
    "M_VLDL_FC": "Free cholesterol in medium VLDL (mmol/l)",
    "M_VLDL_TG": "Triglycerides in medium VLDL (mmol/l)",
}

small_VLDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "S_VLDL_P": "Concentration of small VLDL particles (mmol/l)",
    "S_VLDL_L": "Total lipids in small VLDL (mmol/l)",
    "S_VLDL_PL": "Phospholipids in small VLDL (mmol/l)",
    "S_VLDL_C": "Total cholesterol in small VLDL (mmol/l)",
    "S_VLDL_CE": "Cholesterol esters in small VLDL (mmol/l)",
    "S_VLDL_FC": "Free cholesterol in small VLDL (mmol/l)",
    "S_VLDL_TG": "Triglycerides in small VLDL (mmol/l)",
}

very_small_VLDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "XS_VLDL_P": "Concentration of very small VLDL particles (mmol/l)",
    "XS_VLDL_L": "Total lipids in very small VLDL (mmol/l)",
    "XS_VLDL_PL": "Phospholipids in very small VLDL (mmol/l)",
    "XS_VLDL_C": "Total cholesterol in very small VLDL (mmol/l)",
    "XS_VLDL_CE": "Cholesterol esters in very small VLDL (mmol/l)",
    "XS_VLDL_FC": "Free cholesterol in very small VLDL (mmol/l)",
    "XS_VLDL_TG": "Triglycerides in very small VLDL (mmol/l)",
}

idl = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "IDL_P": "Concentration of IDL particles (mmol/l)",
    "IDL_L": "Total lipids in IDL (mmol/l)",
    "IDL_PL": "Phospholipids in IDL (mmol/l)",
    "IDL_C": "Total cholesterol in IDL (mmol/l)",
    "IDL_CE": "Cholesterol esters in IDL (mmol/l)",
    "IDL_FC": "Free cholesterol in IDL (mmol/l)",
    "IDL_TG": "Triglycerides in IDL (mmol/l)",
}

large_LDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "L_LDL_P": "Concentration of large LDL particles (mmol/l)",
    "L_LDL_L": "Total lipids in large LDL (mmol/l)",
    "L_LDL_PL": "Phospholipids in large LDL (mmol/l)",
    "L_LDL_C": "Total cholesterol in large LDL (mmol/l)",
    "L_LDL_CE": "Cholesterol esters in large LDL (mmol/l)",
    "L_LDL_FC": "Free cholesterol in large LDL (mmol/l)",
    "L_LDL_TG": "Triglycerides in large LDL (mmol/l)",
}

medium_LDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "M_LDL_P": "Concentration of medium LDL particles (mmol/l)",
    "M_LDL_L": "(Total lipids in medium LDL particles mmol/l)",
    "M_LDL_PL": "Phospholipids in medium LDL particles (mmol/l)",
    "M_LDL_C": "Total cholesterol in medium LDL particles (mmol/l)",
    "M_LDL_CE": "Cholesterol esters in medium LDL particles (mmol/l)",
    "M_LDL_FC": "Free cholesterol in medium LDL particles (mmol/l)",
    "M_LDL_TG": "Triglycerides in medium LDL particles (mmol/l)",
}

small_LDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "S_LDL_P": "Concentration of small LDL particles (mmol/l)",
    "S_LDL_L": "Total lipids in small LDL particles (mmol/l)",
    "S_LDL_PL": "Phospholipids in small LDL particles (mmol/l)",
    "S_LDL_C": "Total cholesterol in small LDL particles (mmol/l)",
    "S_LDL_CE": "Cholesterol esters in small LDL particles (mmol/l)",
    "S_LDL_FC": "Free cholesterol in small LDL particles (mmol/l)",
    "S_LDL_TG": "Triglycerides in small LDL particles (mmol/l)",
}

very_large_HDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "XL_HDL_P": "Concentration of very large HDL particles (mmol/l)",
    "XL_HDL_L": "Total lipids in very large HDL particles (mmol/l)",
    "XL_HDL_PL": "Phospholipids in very large HDL particles (mmol/l)",
    "XL_HDL_C": "Total cholesterol in very large HDL particles (mmol/l)",
    "XL_HDL_CE": "Cholesterol esters in very large HDL particles (mmol/l)",
    "XL_HDL_FC": "Free cholesterol in very large HDL particles (mmol/l)",
    "XL_HDL_TG": "Triglycerides in very large HDL particles (mmol/l)",
}

large_HDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "L_HDL_P": "Concentration of large HDL particles (mmol/l)",
    "L_HDL_L": "Total lipids in large HDL particles (mmol/l)",
    "L_HDL_PL": "Phospholipids in large HDL particles (mmol/l)",
    "L_HDL_C": "Total cholesterol in large HDL particles (mmol/l)",
    "L_HDL_CE": "Cholesterol esters in large HDL particles (mmol/l)",
    "L_HDL_FC": "Free cholesterol in large HDL particles (mmol/l)",
    "L_HDL_TG": "Triglycerides in large HDL particles (mmol/l)",
}


medium_HDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "M_HDL_P": "Concentration of medium HDL particles (mmol/l)",
    "M_HDL_L": "Total lipids in medium HDL particles (mmol/l)",
    "M_HDL_PL": "Phospholipids in medium HDL particles (mmol/l)",
    "M_HDL_C": "Total cholesterol in medium HDL particles (mmol/l)",
    "M_HDL_CE": "Cholesterol esters in medium HDL particles (mmol/l)",
    "M_HDL_FC": "Free cholesterol in medium HDL particles (mmol/l)",
    "M_HDL_TG": "Triglycerides in medium HDL particles (mmol/l)",
}

small_HDL = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "S_HDL_P": "Concentration of small HDL particles (mmol/l)",
    "S_HDL_L": "Total lipids in small HDL particles (mmol/l)",
    "S_HDL_PL": "Phospholipids in small HDL particles (mmol/l)",
    "S_HDL_C": "Total cholesterol in small HDL particles (mmol/l)",
    "S_HDL_CE": "Cholesterol esters in small HDL particles (mmol/l)",
    "S_HDL_FC": "Free cholesterol in small HDL particles (mmol/l)",
    "S_HDL_TG": "Triglycerides in small HDL particles (mmol/l)",
}


all_metabolites = {
    "RID": "Participant Roster ID",
    "VISCODE2": "Visit Code",
    "TOTAL_C": "Total Cholesterol (mmol/l)",
    "NON_HDL_C": "Non-HDL Cholesterol (mmol/l)",
    "REMNANT_C": "Remnant cholesterol; non-HDL, non-LDL -cholesterol (mmol/l)",
    "VLDL_C": "Cholesterol in VLDL particles (mmol/l)",
    "CLINICAL_LDL_C": "Clinical LDL Cholesterol (mmol/l)",
    "LDL_C": "Cholesterol in LDL (mmol/l)",
    "HDL_C": "Cholesterol in HDL (mmol/l)",
    "TOTAL_TG": "Total Triglycerides (mmol/l)",
    "VLDL_TG": "Triglycerides in VLDL particles (mmol/l)",
    "LDL_TG": "Triglycerides in LDL particles (mmol/l)",
    "HDL_TG": "Triglycerides in HDL particles (mmol/l)",
    "TOTAL_PL": "Total Phospholipids (mmol/l)",
    "VLDL_PL": "Phospholipids in VLDL particles (mmol/l)",
    "LDL_PL": "Phospholipids in LDL particles (mmol/l)",
    "HDL_PL": "Phospholipids in HDL particles (mmol/l)",
    "TOTAL_CE": "Total Cholesteryl Esters (mmol/l)",
    "VLDL_CE": "Cholesteryl Esters in HDL particles (mmol/l)",
    "LDL_CE": "Cholesteryl Esters in HDL particles (mmol/l)",
    "HDL_CE": "Cholesteryl Esters in HDL particles (mmol/l)",
    "TOTAL_FC": "Total Free Cholesterol (mmol/l)",
    "VLDL_FC": "Free Cholesterol in VLDL particles (mmol/l)",
    "LDL_FC": "Free Cholesterol in LDL particles (mmol/l)",
    "HDL_FC": "Free Cholesterol in HDL particles (mmol/l)",
    "TOTAL_L": "Total Lipids (mmol/l)",
    "VLDL_L": "Lipids in VLDL particles (mmol/l)",
    "LDL_L": "Lipids in LDL particles (mmol/l)",
    "HDL_L": "Lipids in HDL particles (mmol/l)",
    "TOTAL_P": "Total Lipoprotein Particle Concentrations (mmol/l)",
    "VLDL_P": "Very Low Density Lipoprotein Particles (mmol/l)",
    "LDL_P": "Low Density Lipoprotein Particles (mmol/l)",
    "HDL_P": "High Density Lipoprotein Particles(mmol/l)",
    "VLDL_SIZE": "Size of VLDL (nm)",
    "LDL_SIZE": "Size of LDL (nm)",
    "HDL_SIZE": "Size of HDL (nm)",
    "PHOSPHOGLYC": "Phosphoglycerides(mmol/l)",
    "TG_BY_PG": "Ratio of Triglycerides to Phosphoglycerides",
    "CHOLINES": "Cholines (mmol/l)",
    "PHOSPHATIDYLC": "Phosphatidylcholines (mmol/l)",
    "SPHINGOMYELINS": "Sphingomyelins (mmol/l)",
    "APOB": "Apolipoprotein B (g/l)",
    "APOA1": "Apolipoprotein A-1 (g/l)",
    "APOB_BY_APOA1": "Ratio of Apolipoprotein B to Apolipoprotein A-1",
    "TOTAL_FA": "Total Fatty Acids",
    "UNSATURATION": "Estimated Degree of Unsaturation",
    "OMEGA_3": "Omega-3 Fatty Acids (mmol/l)",
    "OMEGA_6": "Omega-6 Fatty Acids (mmol/l)",
    "PUFA": "Polyunsaturated Fatty Acids (mmol/l)",
    "MUFA": "Monounsaturated Fatty Acids; 16:1, 18:1 (mmol/l)",
    "SFA": "Saturated Fatty Acids (mmol/l)",
    "LA": "18:2, Linoleic Acid (mmol/l)",
    "DHA": "22:6, Docosahexaenoic Acid (mmol/l)",
    "OMEGA_3_PCT": "Omega-3 Fatty Acids (%)",
    "OMEGA_6_PCT": "Omega-6 Fatty Acids (%)",
    "PUFA_PCT": "Polyunsaturated Fatty Acids (%)",
    "MUFA_PCT": "Monounsaturated Fatty Acids (%)",
    "SFA_PCT": "Saturated Fatty Acids (%)",
    "LA_PCT": "18:2, Linoleic Acid (%)",
    "DHA_PCT": "22:6, Docosahexaenoic Acid (%)",
    "PUFA_BY_MUFA": "Ratio of Polyunsaturated to Monounsaturated Fatty Acids ",
    "OMEGA_6_BY_OMEGA_3": "Ratio of Omega-6 to Omega-3 Fatty Acids",
    "ALA": "Alanine (mmol/l)",
    "GLN": "Glutamine (mmol/l)",
    "GLY": "Glycine (mmol/l)",
    "HIS": "Histidine (mmol/l)",
    "TOTAL_BCAA": "Total Concentration of Branced-Chain Amino Acids (mmol/l)",
    "ILE": "Isoleucine (mmol/l)",
    "LEU": "Leucine (mmol/l)",
    "VAL": "Valine (mmol/l)",
    "PHE": "Phenylalanine (mmol/l)",
    "TYR": "Tyrosine (mmol/l)",
    "GLUCOSE": "Glucose (mmol/l)",
    "LACTATE": "Lactate (mmol/l)",
    "PYRUVATE": "Pyruvate (mmol/l)",
    "CITRATE": "Citrate (mmol/l)",
    "GLYCEROL": "Glycerol (mmol/l)",
    "BOHBUTYRATE": "β-hydroxybutyrate (mmol/l)",
    "ACETATE": "Acetate (mmol/l)",
    "ACETOACETATE": "Acetoacetate (mmol/l)",
    "ACETONE": "Acetone (mmol/l)",
    "CREATININE": "Creatinine (µmol/l)",
    "ALBUMIN": "Albumin (g/l)",
    "GLYCA": "GlycA Inflammatory Biomarker (mmol/l)",
    "XXL_VLDL_P": "Chylomicrons and extremely large VLDL Particles (mmol/l)",
    "XXL_VLDL_L": "Total lipids in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_PL": "Phospholipids in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_C": "Total cholesterol in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_CE": "Cholesterol esters in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_FC": "Free cholesterol in chylomicrons and extremely large VLDL (mmol/l)",
    "XXL_VLDL_TG": "Triglycerides in chylomicrons and extremely large VLDL (mmol/l)",
    "XL_VLDL_P": "Concentration of very large VLDL particles (mmol/l)",
    "XL_VLDL_L": "Total lipids in very large VLDL  (mmol/l)",
    "XL_VLDL_PL": "Phospholipids in very large VLDL (mmol/l)",
    "XL_VLDL_C": "Total cholesterol in very large VLDL (mmol/l)",
    "XL_VLDL_CE": "Cholesterol esters in very large VLDL (mmol/l)",
    "XL_VLDL_FC": "Free cholesterol in very large VLDL (mmol/l)",
    "XL_VLDL_TG": "Triglycerides in very large VLDL (mmol/l)",
    "L_VLDL_P": "Concentration of large VLDL particles(mmol/l)",
    "L_VLDL_L": "Total lipids in large VLDL (mmol/l)",
    "L_VLDL_PL": "Phospholipids in large VLDL (mmol/l)",
    "L_VLDL_C": "Total cholesterol in large VLDL (mmol/l)",
    "L_VLDL_CE": "Cholesterol esters in large VLDL (mmol/l)",
    "L_VLDL_FC": "Free cholesterol in large VLDL (mmol/l)",
    "L_VLDL_TG": "Triglycerides in large VLDL (mmol/l)",
    "M_VLDL_P": "Concentration of medium VLDL particles (mmol/l)",
    "M_VLDL_L": "Total lipids in medium VLDL (mmol/l)",
    "M_VLDL_PL": "Phospholipids in medium VLDL (mmol/l)",
    "M_VLDL_C": "Total cholesterol in medium VLDL (mmol/l)",
    "M_VLDL_CE": "Cholesterol esters in medium VLDL (mmol/l)",
    "M_VLDL_FC": "Free cholesterol in medium VLDL (mmol/l)",
    "M_VLDL_TG": "Triglycerides in medium VLDL (mmol/l)",
    "S_VLDL_P": "Concentration of small VLDL particles (mmol/l)",
    "S_VLDL_L": "Total lipids in small VLDL (mmol/l)",
    "S_VLDL_PL": "Phospholipids in small VLDL (mmol/l)",
    "S_VLDL_C": "Total cholesterol in small VLDL (mmol/l)",
    "S_VLDL_CE": "Cholesterol esters in small VLDL (mmol/l)",
    "S_VLDL_FC": "Free cholesterol in small VLDL (mmol/l)",
    "S_VLDL_TG": "Triglycerides in small VLDL (mmol/l)",
    "XS_VLDL_P": "Concentration of very small VLDL particles (mmol/l)",
    "XS_VLDL_L": "Total lipids in very small VLDL (mmol/l)",
    "XS_VLDL_PL": "Phospholipids in very small VLDL (mmol/l)",
    "XS_VLDL_C": "Total cholesterol in very small VLDL (mmol/l)",
    "XS_VLDL_CE": "Cholesterol esters in very small VLDL (mmol/l)",
    "XS_VLDL_FC": "Free cholesterol in very small VLDL (mmol/l)",
    "XS_VLDL_TG": "Triglycerides in very small VLDL (mmol/l)",
    "IDL_P": "Concentration of IDL particles (mmol/l)",
    "IDL_L": "Total lipids in IDL (mmol/l)",
    "IDL_PL": "Phospholipids in IDL (mmol/l)",
    "IDL_C": "Total cholesterol in IDL (mmol/l)",
    "IDL_CE": "Cholesterol esters in IDL (mmol/l)",
    "IDL_FC": "Free cholesterol in IDL (mmol/l)",
    "IDL_TG": "Triglycerides in IDL (mmol/l)",
    "L_LDL_P": "Concentration of large LDL particles (mmol/l)",
    "L_LDL_L": "Total lipids in large LDL (mmol/l)",
    "L_LDL_PL": "Phospholipids in large LDL (mmol/l)",
    "L_LDL_C": "Total cholesterol in large LDL (mmol/l)",
    "L_LDL_CE": "Cholesterol esters in large LDL (mmol/l)",
    "L_LDL_FC": "Free cholesterol in (mmol/l)",
    "L_LDL_TG": "Triglycerides in large LDL (mmol/l)",
    "M_LDL_P": "Concentration of medium LDL particles (mmol/l)",
    "M_LDL_L": "(Total lipids in medium LDL particles mmol/l)",
    "M_LDL_PL": "Phospholipids in medium LDL particles (mmol/l)",
    "M_LDL_C": "Total cholesterol in medium LDL particles (mmol/l)",
    "M_LDL_CE": "Cholesterol esters in medium LDL particles (mmol/l)",
    "M_LDL_FC": "Free cholesterol in medium LDL particles (mmol/l)",
    "M_LDL_TG": "Triglycerides in medium LDL particles (mmol/l)",
    "S_LDL_P": "Concentration of small LDL particles (mmol/l)",
    "S_LDL_L": "Total lipids in small LDL particles (mmol/l)",
    "S_LDL_PL": "Phospholipids in small LDL particles (mmol/l)",
    "S_LDL_C": "Total cholesterol in small LDL particles (mmol/l)",
    "S_LDL_CE": "Cholesterol esters in small LDL particles (mmol/l)",
    "S_LDL_FC": "Free cholesterol in small LDL particles (mmol/l)",
    "S_LDL_TG": "Triglycerides in small LDL particles (mmol/l)",
    "XL_HDL_P": "Concentration of very large HDL particles (mmol/l)",
    "XL_HDL_L": "Total lipids in very large HDL particles (mmol/l)",
    "XL_HDL_PL": "Phospholipids in very large HDL particles (mmol/l)",
    "XL_HDL_C": "Total cholesterol in very large HDL particles (mmol/l)",
    "XL_HDL_CE": "Cholesterol esters in very large HDL particles (mmol/l)",
    "XL_HDL_FC": "Free cholesterol in very large HDL particles (mmol/l)",
    "XL_HDL_TG": "Triglycerides in very large HDL particles (mmol/l)",
    "L_HDL_P": "Concentration of large HDL particles (mmol/l)",
    "L_HDL_L": "Total lipids in large HDL particles (mmol/l)",
    "L_HDL_PL": "(Phospholipids in large HDL particles mmol/l)",
    "L_HDL_C": "Total cholesterol in large HDL particles (mmol/l)",
    "L_HDL_CE": "Cholesterol esters in large HDL particles (mmol/l)",
    "L_HDL_FC": "Free cholesterol in large HDL particles (mmol/l)",
    "L_HDL_TG": "Triglycerides in large HDL particles (mmol/l)",
    "M_HDL_P": "Concentration of medium HDL particles (mmol/l)",
    "M_HDL_L": "Total lipids in medium HDL particles (mmol/l)",
    "M_HDL_PL": "Phospholipids in medium HDL particles (mmol/l)",
    "M_HDL_C": "Total cholesterol in medium HDL particles (mmol/l)",
    "M_HDL_CE": "Cholesterol esters in medium HDL particles (mmol/l)",
    "M_HDL_FC": "Free cholesterol in medium HDL particles (mmol/l)",
    "M_HDL_TG": "Triglycerides in medium HDL particles (mmol/l)",
    "S_HDL_P": "Concentration of small HDL particles (mmol/l)",
    "S_HDL_L": "Total lipids in small HDL particles (mmol/l)",
    "S_HDL_PL": "Phospholipids in small HDL particles (mmol/l)",
    "S_HDL_C": "Total cholesterol in small HDL particles (mmol/l)",
    "S_HDL_CE": "Cholesterol esters in small HDL particles (mmol/l)",
    "S_HDL_FC": "Free cholesterol in small HDL particles (mmol/l)",
    "S_HDL_TG": "Triglycerides in small HDL particles (mmol/l)",
    "XXL_VLDL_PL_PCT": "Phospholipids in extremely large VLDL particles (%)",
    "XXL_VLDL_C_PCT": "Total cholesterol in extremely large VLDL particles (%)",
    "XXL_VLDL_CE_PCT": "Cholesterol esters in extremely large VLDL particles (%)",
    "XXL_VLDL_FC_PCT": "Free cholesterol in extremely large VLDL particles (%)",
    "XXL_VLDL_TG_PCT": "Triglycerides in extremely large VLDL particles (%)",
    "XL_VLDL_PL_PCT": "Phospholipids in very large VLDL particles (%)",
    "XL_VLDL_C_PCT": "Total cholesterol in very large VLDL particles (%)",
    "XL_VLDL_CE_PCT": "Cholesterol esters in very large VLDL particles (%)",
    "XL_VLDL_FC_PCT": "Free cholesterol in very large VLDL particles (%)",
    "XL_VLDL_TG_PCT": "Triglycerides in very large VLDL particles (%)",
    "L_VLDL_PL_PCT": "Phospholipids in large VLDL particles (%)",
    "L_VLDL_C_PCT": "Total cholesterol in large VLDL particles (%)",
    "L_VLDL_CE_PCT": "Cholesterol esters in large VLDL particles (%)",
    "L_VLDL_FC_PCT": "Free cholesterol in large VLDL particles (%)",
    "L_VLDL_TG_PCT": "Triglycerides in large VLDL particles (%)",
    "M_VLDL_PL_PCT": "Phospholipids in medium VLDL particle (%)",
    "M_VLDL_C_PCT": "Total cholesterol in medium VLDL particle (%)",
    "M_VLDL_CE_PCT": "Cholesterol esters in medium VLDL particle (%)",
    "M_VLDL_FC_PCT": "Free cholesterol in medium VLDL particle (%)",
    "M_VLDL_TG_PCT": "Triglycerides in medium VLDL particle (%)",
    "S_VLDL_PL_PCT": "Phospholipids in small VLDL particle (%)",
    "S_VLDL_C_PCT": "Total cholesterol in small VLDL particle (%)",
    "S_VLDL_CE_PCT": "Cholesterol esters in small VLDL particle (%)",
    "S_VLDL_FC_PCT": "Free cholesterol in small VLDL particles (%)",
    "S_VLDL_TG_PCT": "Triglycerides in small VLDL particles (%)",
    "XS_VLDL_PL_PCT": "Phospholipids in very small VLDL particles (%)",
    "XS_VLDL_C_PCT": "Total cholesterol in very small VLDL particles (%)",
    "XS_VLDL_CE_PCT": "Cholesterol esters in very small VLDL particles (%)",
    "XS_VLDL_FC_PCT": "Free cholesterol in very small VLDL particles (%)",
    "XS_VLDL_TG_PCT": "Triglycerides in very small VLDL particles (%)",
    "IDL_PL_PCT": "Phospholipids in IDL particles (%)",
    "IDL_C_PCT": "Total cholesterol in IDL particles (%)",
    "IDL_CE_PCT": "Cholesterol esters in IDL particles (%)",
    "IDL_FC_PCT": "Free cholesterol in IDL particles (%)",
    "IDL_TG_PCT": "Triglycerides in IDL particles (%)",
    "L_LDL_PL_PCT": "Phospholipids in large LDL particles (%)",
    "L_LDL_C_PCT": "Total cholesterol in large LDL particles (%)",
    "L_LDL_CE_PCT": "Cholesterol esters in large LDL particles (%)",
    "L_LDL_FC_PCT": "Free cholesterol in large LDL particles (%)",
    "L_LDL_TG_PCT": "Triglycerides in large LDL particles (%)",
    "M_LDL_PL_PCT": "Phospholipids in medium LDL particles (%)",
    "M_LDL_C_PCT": "Total cholesterol in medium LDL particles (%)",
    "M_LDL_CE_PCT": "Cholesterol esters in medium LDL particles (%)",
    "M_LDL_FC_PCT": "Free cholesterol in medium LDL particles (%)",
    "M_LDL_TG_PCT": "Triglycerides in medium LDL particles (%)",
    "S_LDL_PL_PCT": "Phospholipids in small LDL particles (%)",
    "S_LDL_C_PCT": "Total cholesterol in small LDL particles (%)",
    "S_LDL_CE_PCT": "Cholesterol esters in small LDL particles (%)",
    "S_LDL_FC_PCT": "Free cholesterol in small LDL particles (%)",
    "S_LDL_TG_PCT": "Triglycerides in small LDL particles (%)",
    "XL_HDL_PL_PCT": "Phospholipids in very large HDL particles (%)",
    "XL_HDL_C_PCT": "Total cholesterol in very large HDL particles (%)",
    "XL_HDL_CE_PCT": "Cholesterol esters in very large HDL particles (%)",
    "XL_HDL_FC_PCT": "Free cholesterol in very large HDL particles (%)",
    "XL_HDL_TG_PCT": "Triglycerides in very large HDL particles (%)",
    "L_HDL_PL_PCT": "Phospholipids in large HDL particles (%)",
    "L_HDL_C_PCT": "Total cholesterol in large HDL particles (%)",
    "L_HDL_CE_PCT": "Cholesterol esters in large HDL particles (%)",
    "L_HDL_FC_PCT": "Free cholesterol in large HDL particles (%)",
    "L_HDL_TG_PCT": "Triglycerides in large HDL particles (%)",
    "M_HDL_PL_PCT": "Phospholipids in medium HDL particles (%)",
    "M_HDL_C_PCT": "Total cholesterol in medium HDL particles (%)",
    "M_HDL_CE_PCT": "Cholesterol esters in medium HDL particles (%)",
    "M_HDL_FC_PCT": "Free cholesterol in medium HDL particles (%)",
    "M_HDL_TG_PCT": "Triglycerides in medium HDL particles (%)",
    "S_HDL_PL_PCT": "Phospholipids in small HDL particles (%)",
    "S_HDL_C_PCT": "Total cholesterol in small HDL particles (%)",
    "S_HDL_CE_PCT": "Cholesterol esters in small HDL particles (%)",
    "S_HDL_FC_PCT": "Free cholesterol in small HDL particles (%)",
    "S_HDL_TG_PCT": "Triglycerides in small HDL particles (%)",
}
